try {
    // Block of code to try
} catch (err) {
    // Block of code to handle errors
    throw {
        name: "error",
        message: "400"
    };
}
